server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_auth
    username: ${TODO_AUTH_DB_USERNAME}
    password: ${TODO_AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID_GOOGLE}
            client-secret: ${OAUTH2_CLIENT_SECRET_GOOGLE}
            scope: profile,email

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider: DEBUG
