server:
  port: 8080

spring:
  application:
    name: todo-api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path= /auth/**, /users/**, /profile/**

        - id: task-service
          uri: http://localhost:8082
          predicates:
            - Path= /tasks/**, /projects/**, /labels/**

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path= /notifications/**, /alerts/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG